ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('history/', views.my_purchases, name='my_purchases_history'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # Home app URLs
    path('products/', include('products.urls')),  # Products app URLs
    path('auth/', include('authentication.urls')),
    path('profile/', include('usersprofile.urls')),
    path('cart/', include('cart.urls')),
]

# Serve media files in development (ensure this is after other URLs)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from django.utils.timezone import now

class Purchase(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchased_at = models.DateTimeField(default=now)

    def __str__(self):
        return f"{self.user.username} - {self.product.name} - {self.quantity} - {self.purchased_at}"

ecommerce/cart/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from products.models import Product
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Purchase

def get_cart(request):
    cart = request.session.get('cart', {})
    return cart

def view_cart(request):
    cart = get_cart(request)
    products = []
    total_price = 0

    for product_id, quantity in cart.items():
        product = Product.objects.get(id=int(product_id))
        total_price += product.price * quantity
        products.append({'product': product, 'quantity': quantity})

    return render(request, 'cart/cart.html', {'products': products, 'total_price': total_price})


def add_to_cart(request, product_id):
    cart = request.session.get('cart', {})
    product_id = str(product_id)

    if product_id in cart:
        cart[product_id] += 1
    else:
        cart[product_id] = 1

    request.session['cart'] = cart
    messages.success(request, 'Product added successfully.')

    return redirect('cart:view_cart')

def remove_from_cart(request, product_id):
    cart = get_cart(request)
    product_id = str(product_id)

    if product_id in cart:
        del cart[product_id]
        request.session['cart'] = cart
        messages.success(request, 'Product removed successfully.')
    return redirect('cart:view_cart') # aq mgoni shesasworebelia


@login_required
def checkout(request):
    cart = request.session.get('cart', {})

    if not cart:
        messages.warning(request, 'You have nothing in your cart.')
        return redirect('cart:view_cart')

    for product_id, quantity in cart.items():
        product = Product.objects.get(id=product_id)
        total_price = product.price * quantity

        Purchase.objects.create(
            user=request.user,
            product=product,
            quantity=quantity,
            total_price=total_price
        )

    request.session['cart'] = {}
    messages.success(request, 'Thank you for your purchase! :)')
    return redirect('cart:my_purchases_history')

@login_required
def my_purchases(request):
    purchases_list = Purchase.objects.filter(user=request.user).order_by('-purchased_at')

    paginator = Paginator(purchases_list, 5)
    page_number = request.GET.get('page')
    purchases = paginator.get_page(page_number)

    return render(request, 'cart/purchase_history.html', {'purchases': purchases})

ecommerce/cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h2>Your Cart</h2>
    {% if products %}
    <ul>
        {% for item in products %}
        <li>
            <strong>{{ item.product.name }}</strong> (x{{ item.quantity}}) - ${{ item.product.price }} each
            <a href="{% url 'cart:remove_from_cart' item.product.id %}" class="btn btn-danger">Remove</a>
        </li>
        {% endfor %}
    </ul>

    <p><strong>Total: ${{ total_price }}</strong></p>
    <a href="{% url 'cart:checkout' %}" class="btn btn-success">Checkout</a>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}

    <a href="{% url 'products' %}" class="btn btn-primary">Continue shoping</a>

</div>
{% endblock %}

ecommerce/cart/templates/cart/purchase_history.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Purchase History</h2>

    {% if purchases %}
        <ul>
            {% for purchase in purchases %}
                <li>
                    <strong>{{ purchase.product.name }}</strong> - x{{ purchase.quantity }} - ${{ purchase.total_price }}
                    <br>
                    <small>Purchased on: {{ purchase.purchased_at }}</small>
                </li>
            <hr style="border:0; border-top: 3px solid orange; margin: 20px 0">
            {% endfor %}
        </ul>


        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if purchases.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ purchases.previous_page_number }}">Previous</a></li>
                {% endif %}

                <li class="page-item active"><span class="page-link">{{ purchases.number }} of {{ purchases.paginator.num_pages }}</span></li>

                {% if purchases.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ purchases.next_page_number }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ purchases.paginator.num_pages }}">Last</a></li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No purchase history found.</p>
    {% endif %}

    <a href="{% url 'products' %}" class="btn btn-primary">Continue Shopping</a>
</div>
{% endblock %}