ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('history/', views.my_purchases, name='my_purchases_history'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # Home app URLs
    path('products/', include('products.urls')),  # Products app URLs
    path('auth/', include('authentication.urls')),
    path('profile/', include('usersprofile.urls')),
    path('cart/', include('cart.urls')),
]

# Serve media files in development (ensure this is after other URLs)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path
from .views import products_view, add_product

urlpatterns = [
    path('', products_view, name='products'),
    path('category/<int:category_id>/', products_view, name='category_products'),
    path('add/', add_product, name='add_product'),
]

ecommerce/products/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', null=True, blank=True)

    def __str__(self):
        return self.name

ecommerce/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'image', 'category']

ecommerce/products/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Product, Category
from .forms import ProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def products_view(request, category_id=None):
    categories = Category.objects.all()
    category_id = request.GET.get('category')
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 9)
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)


    return render(request, 'products/products.html', {'page_obj': page_obj, 'categories': categories})


def add_product(request):
    if request.user.is_authenticated and request.user.has_perm('products.add_product'):

        if request.method == 'POST':
            form = ProductForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('products')
            else:
                return render(request, 'products/add_product.html', {'form': form})

        else:
            form = ProductForm()
            return render(request, 'products/add_product.html', {'form': form})
    return HttpResponse("You do not have permission to add product")

ecommerce/templates/products/add_product.html
% extends 'base.html'%}

{% block title %} Add New Product {% endblock %}

{% load crispy_forms_tags %}

{% block content %}

    <form method="post" enctype="multipart/form-data">

      {% csrf_token %}
      {{ form|crispy }}

        <button type="submit" class="btn btn-success">Add</button>
        <a href="{% url 'products' %}" class="btn btn-danger">Cancel</a>
    </form>

{% endblock %}

ecommerce/templates/products/products.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
<div class="flex-container">
    <h1 style="margin-left: 10px">Our Products</h1>

    <form method="get">
        <div class="form-group">
            <label for="category" style="margin-left: 10px">Filter by Category:</label>
            <select name="category" id="category" class="form-control">
                <option value="">All Categories</option>
                {% for category in categories %}
                    <option value="{{ category.id }}" {% if category.id == request.GET.category %}selected{% endif %}>
                        {{ category.name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-2" style="margin-left: 25%; margin-bottom: 20px; margin-top: 20px">Filter</button>
    </form>


    {% if user.is_authenticated and perms.core.add_product %}
    <a class="btn btn-primary" href="{% url 'add_product' %}"> Add new product </a>
    {% endif %}
    <div class="row">
    {% for product in page_obj %}
        <div class="col-md-4">
            <div class="card mb-4" style="width: 100%; height: 400px; display: flex; flex-direction: column; margin-top: 30px; margin-bottom: 30px;">
                <div style="width: 100%; height: 200px;">
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" style="width: 100%; height: 100%; object-fit: contain;">
                </div>
                <div class="card-body" style="flex-grow: 1; height: 180px; overflow-y: auto;">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">Description: {{ product.description }}</p>
                    <p class="card-text">Price: ${{ product.price }}</p>
                    <a class="btn btn-primary" href="{% url 'cart:add_to_cart' product.id %}"> Buy </a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="pagination" style="margin-top: 100px">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">First</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">Last</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock %}