ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('history/', views.my_purchases, name='my_purchases_history'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # Home app URLs
    path('products/', include('products.urls')),  # Products app URLs
    path('auth/', include('authentication.urls')),
    path('profile/', include('usersprofile.urls')),
    path('cart/', include('cart.urls')),
]

# Serve media files in development (ensure this is after other URLs)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body data-bs-theme="dark">

  {% include 'navbar.html' %}

  {% block content %}
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" style="color: orange"   href="{% url 'home' %}">sCool Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}" style="color: orange">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color: orange" href="{% url 'products' %}">Products</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: orange">
            Profile
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'profile' %}" style="color: orange">View Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'edit_profile' %}" style="color: orange">Edit Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'cart:my_purchases_history' %}" style="color: orange">Order History</a></li>
          </ul>
        </li>
        {% endif %}
        {% if user.is_authenticated == False %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: orange">
              Login/Register
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'login' %}" style="color: orange">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'registration' %}" style="color: orange">Register</a></li>
            </ul>
          </li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:view_cart' %}" style="color: orange">Cart</a>
          </li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" style="color: orange">Log out</a>
          </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>